### ISSUE TITLE
please set a user agent

### ISSUE THREAD

**Issue by BenTheElder** [quay/container-security-operator#141]
It took me a while to track down https://github.com/quay/container-security-operator/blob/10dfac7858b0e1fdaa13c48a41fb35e9c10eb48b/secscan/wellknown.go#L15 and since there's no user agent set I can't be certain ... but we get a LOT of requests to https://registry.k8s.io for this non-standard endpoint (which isn't in the OCI registry spec nor https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) and they all have generic Go HTTP client as the user agent.

Please consider setting a user agent so server operators know what the client is.

**Comment by BenTheElder** [comment]
... also, is there anything we can do to avoid users attempting to scan this API against registry.k8s.io? This seems to be something quay specific ...?

**Comment by HammerMeetNail** [comment]
Hey @BenTheElder , I created https://issues.redhat.com/browse/PROJQUAY-7472 for us to track. This seems like a straightforward ask, we'll review on Monday and work to roll it into a z-stream release in the coming weeks. We'll talk through hitting that path on other hosts too and get back to you.

**Comment by BenTheElder** [comment]
Thanks!
