### ISSUE TITLE
CSO to trust self signed certificate for private quay registry

### ISSUE THREAD

**Issue by gorantornqvist** [quay/container-security-operator#29]
Hi,
I have installed CSO and added an image from my private quay registry.

Look like CSO cant connect to the private quay registry since I see this error in the operator logs:

level=error msg="Failed to sync layer data" key=quay/quay-clair-test-2-5ggnj err="Get https://quay.apps.mydomain.com/.well-known/app-capabilities: x509: certificate signed by unknown authority"

Is there a way to set an "insecure" option or to add additional CA certs to CSO?

**Comment by abessifi** [comment]
Same issue with the Quay Container Security `v3.3.4`.

**Comment by abessifi** [comment]
Fix: In the same namespace as the operator, create a secret called `container-security-operator-extra-certs` that contains the CA.

**Comment by gorantornqvist** [comment]
Thanks, works!
