### ISSUE TITLE
Kubernetes Version requirement

### ISSUE THREAD

**Issue by niiku** [quay/container-security-operator#51]
Which Kubernetes version is required to run this operator? We're evaluating the usage of this operator in OpenShift 3.11 to get the ImageManifestVuln CRs.

**Comment by niiku** [comment]
Can anyone answer this?

**Comment by kleesc** [comment]
@niiku It should just work with vanilla Kubernetes as long as it's able to serve `apiextensions.k8s.io/v1`

**Comment by niiku** [comment]
@kleesc thank for the answer
