### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by rbaumgar** [quay/container-security-operator#53]
please describe how to uninstall?
CRD?
after unsubscribe the operator, the console still shows "Image Vulnerabilities"

**Comment by furio** [comment]
Run `kubectl delete customresourcedefinition imagemanifestvulns.secscan.quay.redhat.com` to lose the CRD

**Comment by rbaumgar** [comment]
somewhere documented?

**Comment by furio** [comment]
Not in the project, but I had the same issue, and it seems the CRD is not being deleted, this is how i did it

**Comment by modassarrana89** [comment]
Why did we need to delete CRD , shouldn't uninstall do that ??

**Comment by rbaumgar** [comment]
Uninstallation of an operator never deletes CRDs. At least for the operator I am aware of.

**Comment by stevsmit** [comment]
@rbaumgar @modassarrana89 

Happy to announce that this 3 year old issue is now documented in both the Quay docs and OpenShift docs: 

https://github.com/openshift/openshift-docs/pull/80905 (OpenShift PR)

https://github.com/quay/quay-docs/pull/1076/files (Quay PR)

Thanks for filing. 

We might be able to close this issue :)
